sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
deploy:
  provider: script
  script: bash publish_master.sh
  on:
    branch: master